import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Navbar } from "@/components/navbar";
import { Toast } from "@/components/toast";
import { getSession } from "@/libs/auth";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await getSession();
  return (
    <html>
      {/* <body className={inter.className}>{children}</body> */}
      <body>
      <Navbar session={session}/>
      {children}
      <Toast />
      </body>
    </html>
  );
}
